// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSYBGsw1toNSo9qqaXszeuNizKkG_DnG4',
    appId: '1:172505029717:web:b1fdc1fc8b35ef2aa508dc',
    messagingSenderId: '172505029717',
    projectId: 'besuperior-1f589',
    authDomain: 'besuperior-1f589.firebaseapp.com',
    storageBucket: 'besuperior-1f589.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDuF9w7OreoKJ2VNxvKlzNPKEROwcxPoM',
    appId: '1:172505029717:android:5fdd1ba6bff165f1a508dc',
    messagingSenderId: '172505029717',
    projectId: 'besuperior-1f589',
    storageBucket: 'besuperior-1f589.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSYBGsw1toNSo9qqaXszeuNizKkG_DnG4',
    appId: '1:172505029717:web:82493c04e0560da4a508dc',
    messagingSenderId: '172505029717',
    projectId: 'besuperior-1f589',
    authDomain: 'besuperior-1f589.firebaseapp.com',
    storageBucket: 'besuperior-1f589.firebasestorage.app',
  );
}
